version: '3.8' # Recommended

services:
  dbt:
    platform: linux/amd64
    build:
      context: .
      dockerfile: dockerfile.dbt
    container_name: dbt-runner
    environment:
      STORAGE_PATH: "abfss://datastorage@unitycataloginternship.dfs.core.windows.net/uc_tables"
      # Pass INTERNAL UC endpoint and ADMIN token from .env
      # Credentials flow through UC server now for writes
      UC_ENDPOINT: "${UC_SERVER_INTERNAL_ENDPOINT}"
      UC_ADMIN_TOKEN: "eyJraWQiOiJlNGQ3ZjlhYzk5OTMzZGUwMGZlYTI1MzU1MmNjNjdkYzUzOGIxZGNkNTU3NjYyMThhMmRlY2JkZDExOWRjNzZkIiwiYWxnIjoiUlM1MTIiLCJ0eXAiOiJKV1QifQ.eyJzdWIiOiJhZG1pbiIsImlzcyI6ImludGVybmFsIiwiaWF0IjoxNzQ0MDE2Nzc0LCJqdGkiOiI0NjdiNmNlOS1mZmYwLTQzYzctOTg2Yi0zMDg3NzU3NmY5ZDEiLCJ0eXBlIjoiU0VSVklDRSJ9.GbCxv7e5a3Y-ElJ6YinmuG4hjerjBVF2QWqE3Dv-LC_-u4qcbWyh1cVXjQgKFCq4yiHDX7tbhxWppvJ7gRjmSrG0I1EgibhSZbgb8jr-w-obKO_RvcpT9niOPVLJrpqc_AMtM36aPddLcNwU2914kaHeS0fFIEkOi8unhi4x-dX_vs9ne6RChTRNBWiln_MWCYMRBIXRjAw0YcK0eUGlOZfMPJzvGkyUgubQ5PuE5kYBwQJET8p7-s4uyYg7nzSR6mGmPbskOI0ne_trzJro_MM6JsaI7V6mykRKMEe0fyr4mwsx9xJymhfNOHoxTbTcTZ9i6_Glz3qLIG8h4lI0cg"
      AZURE_STORAGE_ACCOUNT: "${AZURE_STORAGE_ACCOUNT}"      # For modified plugin -> ADLS
      AZURE_CLIENT_ID: "${AZURE_STORAGE_CLIENT_ID}"      # For modified plugin -> ADLS
      AZURE_CLIENT_SECRET: "${AZURE_STORAGE_CLIENT_SECRET}"  # For modified plugin -> ADLS
      AZURE_TENANT_ID: "${AZURE_STORAGE_TENANT_ID}"      # For modified plugin -> ADLS
      # AZURE_* vars are NOT needed here for the plugin write path anymore
    env_file:
      - .env # Loads vars for substitution in 'environment' block above
    volumes:
      # Mount your dbt project code relative to compose file location
      - .:/usr/app/dbt
      # Remove local storage volume mount if not needed
      # - /Users/mustafakurtoglu/unitycatalog/etc/data/external/data_storage:/data_storage:rw
    networks:
      - data-network
    working_dir: /usr/app/dbt/dataroots_WoodCorps # Adjust to your dbt project location within the mount
    depends_on:
      - unity-catalog

  unity-catalog:
    build:
      context: .
      dockerfile: dockerfile.uc
    # Rename container for clarity and use in endpoint
    container_name: unity-catalogz
    working_dir: /app/unitycatalog
    ports:
      - "8080:8080"
    volumes:
      # Mount ONLY the server.properties file from host to container (read-only)
      - ./uc-conf/server.properties:/app/unitycatalog/etc/conf/server.properties:ro
    networks:
      - data-network
    # Healthcheck removed for simplicity, can be added back later if needed.
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8080/health"] # Adjust test command as needed
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    #   start_period: 30s # Give more time to start

networks:
  data-network:
    driver: bridge

volumes:
  uc-data: # Define the named volume