    
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'woodcorps'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'woodcorps'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]



vars:
  storage_path: "{{ env_var('STORAGE_PATH') }}"  # Maps env var to a dbt variable

seeds:
  woodcorps:
    materialized: seed
    raw_Woodcorp_O2C_Case_table:
       +column_types:
          ORDER_VALUE: varchar(52)
          UNIT_PRICE: varchar(52)

models:
  woodcorps:

    staging:
        materialized: table
        +catalog: unity
        +schema: woodcorps    
    woodcorpsmodels:
        materialized: table
        +catalog: unity
        +schema: woodcorps
    jafflemodels:
        materialized: table
        +catalog: unity
        +schema: jaffle

