version: '3'

services:
  dbt:
    platform: linux/amd64
    build:
      context: .
      dockerfile: dockerfile.dbt
    environment:
        #Change this to your desired path to store the data
      STORAGE_PATH: "/Users/mustafakurtoglu/github_mustafa/unity_catalog_template/docker-setup/docker_files/data"
      # Pass INTERNAL UC endpoint and ADMIN token from .env
      # Credentials flow through UC server now for writes. If you were to turn on auth, you should replace the token with the admin token.
      UC_ENDPOINT: "http://host.docker.internal:8080"
      UC_ADMIN_TOKEN: "not-used"
    env_file:
      - .env # Loads vars for substitution in 'environment' block above. Token and secrets can be passed through this
    volumes:
        #Change this to your desired path to store the data --> both side of :
        #Note: This part is not needed if you are using Azure as storage
      - /Users/mustafakurtoglu/github_mustafa/unity_catalog_template/docker-setup/docker_files/data:/Users/mustafakurtoglu/github_mustafa/unity_catalog_template/docker-setup/docker_files/data
    container_name: dbt-container
    networks:
      - data-network
      
      
  unity-catalog:
    build:
      context: .
      dockerfile: dockerfile.uc
    working_dir: /app/unitycatalog
    ports:
      - "8080:8080"
    container_name: unity-catalog-container
    networks:
      - data-network
      
  unity-catalog-ui:
    build:
      context: .
      dockerfile: dockerfile.ucui
      args:
        UC_HOST: "http://unity-catalog-container:8080"
    ports:
      - "3000:3000" # Host:Container for accessing the UI
    container_name: unity-catalog-ui-container
    networks:
      - data-network
    depends_on: 
      - unity-catalog

networks:
  data-network:
    driver: bridge
