version: '3.8' # Recommended

services:
  dbt:
    platform: linux/amd64
    build:
      context: .
      dockerfile: dockerfile.dbt
    container_name: dbt-runner
    environment:
      STORAGE_PATH: "/Users/mustafakurtoglu/Downloads/dataroots_setup_docker/unity_catalog_template_copy/docker_files/tables_destination"
      # Pass INTERNAL UC endpoint and ADMIN token from .env
      # Credentials flow through UC server now for writes
      UC_ENDPOINT: "http://unity-catalogz:8080"
      UC_ADMIN_TOKEN: ""
    env_file:
      - .env # Loads vars for substitution in 'environment' block above
    volumes:
      # Mount your dbt project code relative to compose file location
      - .:/usr/app/dbt
      # Remove local storage volume mount if not needed
      # - /Users/mustafakurtoglu/unitycatalog/etc/data/external/data_storage:/data_storage:rw
    networks:
      - data-network
    working_dir: /usr/app/dbt/dataroots_WoodCorps # Adjust to your dbt project location within the mount
    depends_on:
      - unity-catalog

  unity-catalog:
    build:
      context: .
      dockerfile: dockerfile.uc
    # Rename container for clarity and use in endpoint
    container_name: unity-catalogz
    working_dir: /app/unitycatalog
    ports:
      - "8080:8080"
    volumes:
      # Mount ONLY the server.properties file from host to container (read-only)
      - ./uc-conf/server.properties:/app/unitycatalog/etc/conf/server.properties:ro
    networks:
      - data-network
    # Healthcheck removed for simplicity, can be added back later if needed.
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8080/health"] # Adjust test command as needed
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    #   start_period: 30s # Give more time to start

networks:
  data-network:
    driver: bridge

volumes:
  uc-data: # Define the named volume